### ISSUE TITLE
Commit details view stays blank (10.6, Safari 5.1)

### ISSUE THREAD

**Issue by Ronan-** [laullon/gitx#92] opened 2011-07-21 09:30 UTC
I can't get the details view from a commit since I updated Safari to 5.1, the bottom pane just stays empty.

**Comment by AlekSi** [comment] 2011-07-21 10:08
Same here. :(

**Comment by pwagland** [comment] 2011-07-21 11:47
This is a duplicate of issue 77.

**Closed as completed** 2011-07-25 08:27 UTC
