### ISSUE TITLE
Refreshing does not update "master" tag in History view

### ISSUE THREAD

**Issue by indirect** [laullon/gitx#12] opened 2011-03-18 03:58 UTC
When I add a commit using the "Commit" view, and then switch back to the "History" view, my commit is shown, but tagged as somehow being beyond "master". Even refreshing with ⌘R doesn't update the master tag -- instead, it simply scrolls the view down to the commit that is already tagged master. Here's what the view looks like before I try to refresh:

![history view](https://img.skitch.com/20110318-j8jx93b3p3fjsahn5hhjt36274.jpg)

**Comment by targeter** [comment] 2011-03-22 08:25
Same here, but for _all_ labels on the tree.

**Comment by targeter** [comment] 2011-03-22 08:26
Hmm, I think this is a duplicate of https://github.com/laullon/gitx/issues#issue/7

**Comment by sj26** [comment] 2011-04-14 00:56
+1

**Comment by laullon** [comment] 2011-04-18 22:19
solved on v0.8.2

**Closed as completed by laullon** 2011-04-18 22:19 UTC
